# Generated by Django 5.1.6 on 2025-02-06 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_event_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='events',
            field=models.ManyToManyField(to='event.event'),
        ),
    ]
